name: Create binary for release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      retention_days:
        description: 'Retention duration (in days)'
        required: true
        default: '30'
      node_version:
        description: 'NodeJS version'
        required: true
        default: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version || '20.x' }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the extension
        run: pnpm run zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .output/wise-favorites-extension-*

      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          path: .output/wise-favorites-extension-*
          retention-days: ${{ inputs.retention_days || 30 }}